### ISSUE TITLE
Camera di chuyển theo người chơi

### ISSUE THREAD

**Issue by TruongTheTan** [TruongTheTan/FlastSurvival#4]
- Tìm cách khiến Camera di chuyển theo người chơi. Trong **cheatsheet** đã có, có thể tham khảo thêm trên mạng, tìm phần Camera Follow.
- Test sử dụng bàn phím để di chuyển trước (record lại video), sau đó test trên mobile (record lại video).
- Tạo **"Pull Request"** kèm theo 2 video trên.
- Nếu phải tải Asset từ bên ngoài thì để vào trong folder **3rd Party**.

**Comment by TruongTheTan** [comment]
@Seth-Etherald tạm thời bỏ record test trên mobile nhé

**Comment by Seth-Etherald** [comment]
> @Seth-Etherald tạm thời bỏ record test trên mobile nhé
Đã rõ

**Comment by TruongTheTan** [comment]
@Seth-Etherald phần di chuyển người ô có thể ko cần làm tới, cứ tạm thời cho quả bóng (ví dụ) di chuyển đến góc nào đó r để camera đi theo sau
