### ISSUE TITLE
Nhân vật bất động khi dùng joyStick mobile

### ISSUE THREAD

**Issue by TruongTheTan** [TruongTheTan/FlastSurvival#78]
**Đã tìm ra nguyên nhân:**
 - Do script Camera Follow Player.
 - Code di chuyển nhân vật đang bị comment (ko biết ai động vào).

**Cách xử lý:**
- Tạm thời bỏ script Camera Follow Player ra khỏi Main Camera.
- UnComment lại code di chuyển bằng JoyStick.

**Record lại video sau khi làm xong.**

**Comment by TruongTheTan** [comment]
@anh3214 Ô có thể hỏi tùng về camera di chuyển theo player (Vì tùng làm phần này). Có gì nhắn lại tôi qua face

**Comment by TruongTheTan** [comment]
@anh3214 Code di chuyển đã về bình thường, ô sửa lại phần Camera, làm cho nó di chuyển theo người chơi

**Comment by anh3214** [comment]
Confirm

**Comment by Seth-Etherald** [comment]
Camera, player và enemies đều di chuyển với tốc độ xấp xỉ nhau, không có vật cố định để reference dẫn đến việc tạo ra cảm giác nhân vật không di chuyển, không phải là bug.
