### ISSUE TITLE
Thêm sát thương cho mỗi khẩu súng

### ISSUE THREAD

**Issue by TruongTheTan** [TruongTheTan/FlastSurvival#86]
- Mỗi khi random ra 1 loại súng, kiếm đều sẽ có sức sát thương riêng (thông số đã có trên doc).
- Thêm sẵn các properties cần thiết để sau này có thể upgrade súng ().
- Khi bắn ra đạn, đạn sẽ chứa sát thương của súng đang cầm.

**Không cần làm phần upgrade súng**

**Record lại video sau khi làm xong**

**Comment by TruongTheTan** [comment]
@Seth-Etherald ô tiện thể làm phần enemy bị damage bởi súng luôn nhé.

**Comment by Seth-Etherald** [comment]
> @Seth-Etherald ô tiện thể làm phần enemy bị damage bởi súng luôn nhé

Ok
